routes/web.php
<?php

use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\DriverController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Authenticated routes
Route::middleware('web')->group(function () {


    // تسجيل الدخول لمسءول النظام
    Route::get('/', [UserController::class, 'showLoginForm'])->name('showLoginForm');
    Route::get('admin/login', [UserController::class, 'showLoginForm'])->name('showLoginForm');
    Route::post('admin/login', [UserController::class, 'login'])->name('doLogin');
    //    تسجيل الخروج لمسءول النظام
    Route::get('/logout', [UserController::class, 'logout'])->name('logout');

    // Dashboard route (protected by auth middleware)
    Route::middleware(['auth'])->group(function () {
        // لوحة التحكم
        Route::prefix('admin')->group(function () {
            Route::get('/dashboard', [HomeController::class, 'home'])->name('homeDashboard');
            Route::resource('users', ClientController::class);
            Route::resource('drivers', DriverController::class);
            Route::resource('orders', OrderController::class);
        });
    });

});

app/Http/Controllers/Admin/DriverController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\DriverCar;
use App\Models\User;
use Illuminate\Http\Request;

class DriverController extends Controller
{
    public function index()
    {
        $drivers = User::where('user_type','driver')->latest()->get();
        $active = 'drivers';
        return view('admin.drivers.index', compact('drivers', 'active'));
    }

    public function create()
    {
        $active = 'drivers';
        return view('admin.drivers.create', compact('active'));
    }

    public function store(Request $request)
    {
        // Validate the request data
        $request->validate([
            'name' => 'required|string',
            'password' => 'required|string|min:6',
            'phone' => 'required|string|unique:users,phone',
            'identity_number' => 'required|digits:14|unique:users,identity_number',
            'image' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:8192',
            'plate_number' => 'required|string',
            'car_type' => 'required|string',
            'driving_license' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:8192',
            'car_insurance' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:8192',
            'accessories' => 'array',
            'accessories.*' => 'string',
        ]);
        // Create a new user
        $driver = User::create([
            'name' => $request->input('name'),
            'user_type' => 'driver',
            'password' => bcrypt($request->input('password')),
            'phone' => $request->input('phone'),
            'identity_number' => $request->input('identity_number'),
        ]);

        // Upload and store the image if provided
        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $imageName = time() . '.' . $image->getClientOriginalExtension();
            $image->move(public_path('uploads'), $imageName);
            $driver->update([
                'image' => $imageName
            ]);
        }


        // Create and Save the driver car to the database
        $driverCar = DriverCar::create([
            'driver_id' => $driver->id,
            'plate_number' => $request->plate_number,
            'car_type' => $request->car_type,
        ]);

        // Upload and store the driving_license if provided
        if ($request->hasFile('driving_license')) {
            $driving_license = $request->file('driving_license');
            $driving_license_name = \Str::random(5) . '_' . time() . '.' . $driving_license->getClientOriginalExtension();
            $driving_license->move(public_path('uploads'), $driving_license_name);
            $driverCar->driving_license = $driving_license_name;
            $driverCar->save();
        }


        // Upload and store the car_license if provided
        if ($request->hasFile('car_license')) {
            $car_license = $request->file('car_license');
            $car_license_name = \Str::random(5) . '_' . time() . '.' . $car_license->getClientOriginalExtension();
            $car_license->move(public_path('uploads'), $car_license_name);
            $driverCar->car_license = $car_license_name;
            $driverCar->save();
        }
        foreach ($request->accessories as $key => $accessory) {
            $driverCar->accessories()->create([
                'accessory' => $accessory
            ]);
        }

        return redirect()->route('drivers.index')->with('success', 'تم اضافة السائق بنجاح.');
    }


    public function show($id)
    {
        $user = User::findOrFail($id);
        $active = 'drivers';
        return view('admin.drivers.show', compact('user', 'active'));
    }

    public function edit($id)
    {
        $driver = User::findOrFail($id);
        $accessories = $driver->car?->accessories->map(function ($accessory) {
            return $accessory->accessory;
        })->toArray();

        $active = 'drivers';
        return view('admin.drivers.edit', compact('driver','accessories', 'active'));
    }

    public function update(Request $request, $id)
    {
        // Find the user by ID
        $user = User::findOrFail($id);
        // Validate the request data
        $request->validate([
            'name' => 'required',
            'password' => 'nullable|string|min:6',
            'phone' => 'required|string|unique:users,phone,' . $user->id,
            'identity_number' => 'required|digits:14|unique:users,identity_number,' . $user->id,
            'image' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:8192',
            'plate_number' => 'required|string',
            'car_type' => 'required|string',
            'driving_license' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:8192',
            'car_insurance' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:8192',
            'accessories' => 'array',
            'accessories.*' => 'string',
        ]);

        $user->update([
            'name' => $request->input('name') ?? $user->name,
            'phone' => $request->input('phone') ?? $user->phone,
            'identity_number' => $request->input('identity_number') ?? $user->identity_number,
            'password' => $request->input('password') ? bcrypt($request->input('password')) : $user->password,
        ]);

        // Upload and store the new image if provided
        if ($request->hasFile('image')) {
            // Delete the old image if exists
            if ($user->image) {
                unlink(public_path('uploads/' . $user->image));
            }
            // Upload and store the new image
            $image = $request->file('image');
            $imageName = time() . '.' . $image->getClientOriginalExtension();
            $image->move(public_path('uploads'), $imageName);
            $user->image = $imageName;
            $user->save();
        }
        // Create and Save the driver car to the database
        $driverCar = $user->car()->updateOrCreate([
            'driver_id'   => $user->id,
        ],[
            'plate_number' => $request->plate_number,
            'car_type' => $request->car_type,
        ]);

        // Upload and store the driving_license if provided
        if ($request->hasFile('driving_license')) {
            $driving_license = $request->file('driving_license');
            $driving_license_name = \Str::random(5) . '_' . time() . '.' . $driving_license->getClientOriginalExtension();
            $driving_license->move(public_path('uploads'), $driving_license_name);
            $driverCar->driving_license = $driving_license_name;
            $driverCar->save();
        }


        // Upload and store the car_license if provided
        if ($request->hasFile('car_license')) {
            $car_license = $request->file('car_license');
            $car_license_name = \Str::random(5) . '_' . time() . '.' . $car_license->getClientOriginalExtension();
            $car_license->move(public_path('uploads'), $car_license_name);
            $driverCar->car_license = $car_license_name;
            $driverCar->save();
        }

        $driverCar->accessories()->delete();

        foreach ($request->accessories as $key => $accessory) {
            $driverCar->accessories()->create([
                'accessory' => $accessory
            ]);
        }

        // Redirect to the index route
        return redirect()->route('drivers.index')->with('success', 'تم تعديل السائق بنجاح');
    }


    public function destroy($id)
    {
        $user = User::findOrFail($id);
        dd($user);
        // Delete the associated image if it exists
        if ($user->image) {
            $imagePath = public_path('uploads/' . $user->image);
            if (file_exists($imagePath)) {
                unlink($imagePath);
            }
        }
        $user->car()->delete();
        $user->delete();

        return redirect()->route('drivers.index')->with('success', 'تم مسح السائق بنجاح.');
    }
}

app/Http/Controllers/Api/Driver/AuthDriverController.php
<?php

namespace App\Http\Controllers\Api\Driver;

use App\Http\Controllers\Controller;
use App\Http\Resources\User\UserResource;
use App\Models\DriverCar;
use App\Models\User;
use Illuminate\Http\Request;

class AuthDriverController extends Controller
{
    public function register(Request $request)
    {
        // Validate the incoming request data
        $data = $request->validate([
            'name' => 'required|string|max:255',
            'phone' => 'required|string|max:15|unique:users,phone',
            'password' => 'required|string|min:6|confirmed',
            'identity_number' => 'required|integer|digits:14|unique:users,identity_number',
        ]);
        // Create and Save the driver to the database
        $user = User::create($data + [
                'user_type' => 'driver',
            ]);
        // Return a response indicating success

        return response()->json([
            'status' => true,
            "message" => ' تم تسجيل السائق بنجاح برجاء اكمال التسجيل',
            'data' => [
                'user' => UserResource::make($user)
            ]
        ], 200);
    }

    public function completeRegistration(Request $request)
    {
        // Validate the incoming request data
        $data = $request->validate([
            'driver_id' => 'required|exists:users,id',
            'plate_number' => 'required|string',
            'car_type' => 'required|string',
            'driving_license' => 'nullable|image',
            'car_license' => 'nullable|image',
            'accessories' => 'required|array',
            'accessories.*' => 'required',
        ]);

        // Create and Save the driver car to the database
        $driverCar = DriverCar::create([
            'driver_id' => $data['driver_id'],
            'plate_number' => $data['plate_number'],
            'car_type' => $data['car_type'],
        ]);

        // Upload and store the driving_license if provided
        if ($request->hasFile('driving_license')) {
            $driving_license = $request->file('driving_license');
            $driving_license_name = \Str::random(5) . '_' . time() . '.' . $driving_license->getClientOriginalExtension();
            $driving_license->move(public_path('uploads'), $driving_license_name);
            $driverCar->driving_license = $driving_license_name;
            $driverCar->save();
        }


        // Upload and store the car_license if provided
        if ($request->hasFile('car_license')) {
            $car_license = $request->file('car_license');
            $car_license_name = \Str::random(5) . '_' . time() . '.' . $car_license->getClientOriginalExtension();
            $car_license->move(public_path('uploads'), $car_license_name);
            $driverCar->car_license = $car_license_name;
            $driverCar->save();
        }
        foreach ($data['accessories'] as $key => $accessory) {
            $driverCar->accessories()->create([
                'accessory' => $accessory
            ]);
        }

        return response()->json([
            'status' => true,
            "message" => ' تم تسجيل السائق بنجاح',
            'data' => ""
        ], 200);
    }

    public function login(Request $request)
    {
        // Validate the incoming request data
        $request->validate([
            'phone' => 'required|string|max:15',
            'password' => 'required|string',
        ]);

        // Attempt to authenticate the user
        if (\Auth::attempt([
            'phone' => $request->input('phone'),
            'password' => $request->input('password'),
            'user_type' => 'driver',
        ])) {
            // Generate a new Sanctum token for the authenticated user
            $user = auth()->user();
            $token = $user->createToken('auth-token')->plainTextToken;

            return response()->json([
                'status' => true,
                "message" => 'تم الدخول بنجاح',
                'data' => [
                    'token' => $token,
                    'user' => UserResource::make($user)
                ]
            ], 200);
        }

        // Authentication failed
        return response()->json([
            'status' => true,
            "message" => 'تأكد من البيانات المدخلة',
            'data' => ""
        ], 401);
    }

    public function resetPassword(Request $request)
    {
        // Validate the incoming request data
        $request->validate([
            'phone' => 'required|string|max:15',
        ]);

        $user = User::firstWhere('phone', $request->phone);
        if (!$user) {
            return response()->json([
                'status' => false,
                "message" => 'لم يتم العثور على هذا الرقم',
                'data' => ""
            ], 404);
        }
        $new_password = rand(100000, 999999);
        $user->update([
            'password' => bcrypt($new_password)
        ]);

        return response()->json([
            'status' => true,
            "message" => 'تم ارسال الرقم السري الجديد في رسالة نصية',
            'data' => ['new_password' => $new_password]
        ], 200);

    }

    public function logout()
    {
        auth()->user()->tokens()->delete();
        return response()->json([
            'status' => true,
            "message" => 'تم تسجيل الخروج بنجاح',
            'data' => ""
        ], 200);
    }
}

app/Http/Controllers/Api/Driver/OrderDriverController.php
<?php

namespace App\Http\Controllers\Api\Driver;

use App\Http\Controllers\Controller;
use App\Http\Resources\Driver\OrderResource;
use App\Http\Resources\Driver\WalletResource;
use App\Models\Order;
use Illuminate\Http\Request;

class OrderDriverController extends Controller
{
    public function index(Request $request)
    {
        $orders = Order::where('status', 'pending')->whereNull('driver_id')->get();
        return response()->json([
            'status' => true,
            "message" => '',
            'data' => OrderResource::collection($orders)
        ], 200);
    }

    public function getOrders(Request $request)
    {
        $orders = Order::when($request->status, function ($q) use ($request) {
            return $q->where('status', $request->status);
        })->where('driver_id',auth()->id())->get();

        return response()->json([
            'status' => true,
            "message" => '',
            'data' => OrderResource::collection($orders)
        ], 200);
    }

    public function assignOrder($order_id)
    {
        $order = Order::find($order_id);
        if ($order->driver_id != null)
            return response()->json([
                'status' => false,
                "message" => 'تم تعيين الطلب لسائق اخر',
                'data' => ""
            ], 200);

        $order->update([
            'driver_id' => auth()->id(),
            'status' => 'in_progress'
        ]);
        return response()->json([
            'status' => true,
            "message" => 'تم قبول الطلب بنجاح',
            'data' => ""
        ], 200);
    }

    public function completeOrder($order_id)
    {
        $order = Order::find($order_id);

        $array = ['cash','vodafone'];
        // Get a random key from the array
        $randomKey = array_rand($array);
        // Get the value corresponding to the random key
        $randomValue = $array[$randomKey];

        $order->update([
            'status' => 'completed',
            'payment_method' => $randomValue,
        ]);
        return response()->json([
            'status' => true,
            "message" => 'تم تسليم الطلب بنجاح',
            'data' => ""
        ], 200);
    }


    public function getWalletBalance()
    {
        $orders = Order::where([
            'driver_id' => auth()->id(),
            'status' => 'completed'
        ])->get();

        return response()->json([
            'status' => true,
            "message" => '',
            'data' => WalletResource::collection($orders)
        ], 200);
    }
}

resources/views/admin/drivers/create.blade.php
@extends('admin.layouts.app')
<style>
    .checkbox-container {
        display: grid;
        grid-template-columns: repeat(4, 1fr); /* Four checkboxes per row */
        gap: 5px; /* Adjust as needed */
    }

    .checkbox-container input[type="checkbox"] {
        display: none; /* Hide the default checkboxes */
    }

    .checkbox-container label {
        display: block;
        background-color: #f0f0f0; /* Optional background color */
        padding: 5px 10px;
        cursor: pointer;
    }

    .checkbox-container input[type="checkbox"]:checked + label {
        background-color: #007BFF; /* Change background color when checkbox is checked */
    }
</style>

@section('content')
    <!-- /.card-header -->

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">الرئيسية - اضافة السائقين</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/dashboard">الرئيسية</a></li>
                        <li class="breadcrumb-item active"> اضافة السائقين</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <!-- form start -->
                <form role="form" method='post' action="{{ route('drivers.store') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="card-body">
                        @if($errors->any())
                            <div class="alert alert-danger text-center">
                                <ul>
                                    @foreach($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <!-- Name -->
                        <div class="form-group">
                            <label for="name">الاسم</label>
                            <input type="text" required name="name" value="{{ old('name') }}" class="form-control"/>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputFile">الصورة </label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="exampleInputFile" name="image">
                                    <label class="custom-file-label" for="exampleInputFile"></label>
                                </div>
                                <div class="input-group-append">
                                    <br><br>
                                </div>
                            </div>
                        </div>
                        <!-- Phone Number -->
                        <div class="form-group">
                            <label for="phone">رقم الهاتف</label>
                            <input type="text" required name="phone" value="{{ old('phone') }}"
                                   class="form-control"/>
                        </div>

                        <div class="form-group">
                            <label for="identity_number">الرقم القومي</label>
                            <input type="text" required name="identity_number" value="{{ old('identity_number') }}"
                                   class="form-control"/>
                        </div>

                        <div class="form-group">
                            <label for="password">كلمة المرور</label>
                            <input type="password" required name="password" class="form-control"/>
                        </div>

                        <h4>بيانات السيارة</h4>

                        <div class="form-group">
                            <label for="plate_number">رقم اللوحة</label>
                            <input type="text" required name="plate_number" value="{{ old('plate_number') }}"
                                   class="form-control"/>
                        </div>
                        <div class="form-group">
                            <label for="plate_number">نوع السيارة</label>
                            <select name="car_type" class="form-control">
                                <option selected disabled>اختر نوع السيارة</option>
                                <option value="ربع نقل">ربع نقل</option>
                                <option value="جامبو">جامبو</option>
                                <option value="">نقل كبير</option>
                                <option value="سوزوكي">سوزوكي</option>
                                <option value="مقطورة كبيرة">مقطورة كبيرة</option>
                                <option value="قلاب">قلاب</option>
                                <option value="جرار">جرار</option>
                                <option value="مازدا">مازدا</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="accessories">الكماليات</label>
                            <div class="checkbox-container">
                                <input type="checkbox" id="accessory1" name="accessories[]" value="بوم">
                                <label for="accessory1">بوم</label>

                                <input type="checkbox" id="accessory2" name="accessories[]" value="كساتن">
                                <label for="accessory2">كساتن</label>

                                <input type="checkbox" id="accessory3" name="accessories[]" value="شرايط">
                                <label for="accessory3">شرايط</label>

                                <input type="checkbox" id="accessory4" name="accessories[]" value="جنازير">
                                <label for="accessory4">جنازير</label>

                                <input type="checkbox" id="accessory5" name="accessories[]" value="مشمع">
                                <label for="accessory5">مشمع</label>

                                <input type="checkbox" id="accessory6" name="accessories[]" value="زوي">
                                <label for="accessory6">زوي</label>

                                <input type="checkbox" id="accessory7" name="accessories[]" value="سلب">
                                <label for="accessory7">سلب</label>

                                <input type="checkbox" id="accessory8" name="accessories[]" value="سيلات">
                                <label for="accessory8">سيلات</label>

                                <input type="checkbox" id="accessory9" name="accessories[]" value="كاميرا">
                                <label for="accessory9">كاميرا</label>

                                <input type="checkbox" id="accessory10" name="accessories[]" value="انذار رجوع للخلف">
                                <label for="accessory10">انذار رجوع للخلف</label>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputFile">رخصة السيارة </label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="exampleInputFile"
                                           name="car_license">
                                    <label class="custom-file-label" for="exampleInputFile"></label>
                                </div>
                                <div class="input-group-append">
                                    <br><br>
                                </div>
                            </div>
                        </div>


                        <div class="form-group">
                            <label for="exampleInputFile">رخصة القيادة </label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="exampleInputFile"
                                           name="driving_license">
                                    <label class="custom-file-label" for="exampleInputFile"></label>
                                </div>
                                <div class="input-group-append">
                                    <br><br>
                                </div>
                            </div>
                        </div>

                        <input type="hidden" name="user_type" value="driver">
                        <div>
                            <button type="submit" class="btn btn-primary">تأكيد</button>
                        </div>
                    </div>

                    <!-- /.card-body -->
                </form>
            </div>
        </div>
    </section>
    <!-- /.card -->
@endsection

resources/views/admin/drivers/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark"> الرئيسية - قائمة العملاء</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/dashboard">الرئيسية</a></li>
                        <li class="breadcrumb-item active">قائمة العملاء</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- /.content-header -->
    @include('admin.layouts.message')
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title" style="float: right">قائمة العملاء</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>الاسم</th>
                                <th>الرقم القومي</th>
                                <th>الموبايل</th>
                                <th>نوع السيارة</th>
                                <th>مجموع الطلبات</th>
                                <th>الاجراء المتخذ</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($drivers as $user)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->identity_number }}</td>
                                    <td>{{ $user->phone }}</td>
                                    <td>{{ $user->car?->car_type}}</td>
                                    <td>{{ $user->completed_driver_orders->sum('price') }}</td>
                                    <td>
                                        <a href="{{ route('drivers.edit', $user->id) }}" class="btn btn-warning btn-sm">تعديل</a>
                                        <form action="{{ route('drivers.destroy', $user->id) }}" method="post" style="display: inline-block;">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('هل أنت متأكد؟')">حذف</button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="7" class="text-center">لا يوجد بيانات</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection