routes/web.php
<?php

use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\DriverController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Authenticated routes
Route::middleware('web')->group(function () {


    // تسجيل الدخول لمسءول النظام
    Route::get('/', [UserController::class, 'showLoginForm'])->name('showLoginForm');
    Route::get('admin/login', [UserController::class, 'showLoginForm'])->name('showLoginForm');
    Route::post('admin/login', [UserController::class, 'login'])->name('doLogin');
    //    تسجيل الخروج لمسءول النظام
    Route::get('/logout', [UserController::class, 'logout'])->name('logout');

    // Dashboard route (protected by auth middleware)
    Route::middleware(['auth'])->group(function () {
        // لوحة التحكم
        Route::prefix('admin')->group(function () {
            Route::get('/dashboard', [HomeController::class, 'home'])->name('homeDashboard');
            Route::resource('users', ClientController::class);
            Route::resource('drivers', DriverController::class);
            Route::resource('orders', OrderController::class);
        });
    });

});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];


    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    public function driver_orders()
    {
        return $this->hasMany(Order::class,'driver_id');
    }


    public function completed_driver_orders()
    {
        return $this->hasMany(Order::class,'driver_id')->where('status','completed');
    }

    public function car()
    {
        return $this->hasOne(DriverCar::class,'driver_id');
    }
}

app/Http/Controllers/Api/User/AuthController.php
<?php

namespace App\Http\Controllers\Api\User;

use App\Http\Controllers\Controller;
use App\Http\Resources\User\UserResource;
use App\Models\User;
use Illuminate\Http\Request;

class AuthController extends Controller
{
    public function register(Request $request)
    {
        // Validate the incoming request data
        $data = $request->validate([
            'name' => 'required|string|max:255',
            'phone' => 'required|string|max:15|unique:users,phone',
            'password' => 'required|string|min:6|confirmed',
        ]);
        // Create and Save the user to the database
        User::create($data);
        // Return a response indicating success

        return response()->json([
            'status' => true,
            "message" => 'تم التسجيل بنجاح',
            'data' => ""
        ], 200);
    }

    public function login(Request $request)
    {
        // Validate the incoming request data
        $request->validate([
            'phone' => 'required|string|max:15',
            'password' => 'required|string',
        ]);

        // Attempt to authenticate the user
        if (\Auth::attempt(['phone' => $request->input('phone'), 'password' => $request->input('password')])) {
            // Authentication passed

            // Generate a new Sanctum token for the authenticated user
            $user = auth()->user();
            $token = $user->createToken('auth-token')->plainTextToken;

            return response()->json([
                'status' => true,
                "message" => 'تم الدخول بنجاح',
                'data' => [
                    'token' => $token,
                    'user' => UserResource::make($user)
                ]
            ], 200);
        }

        // Authentication failed
        return response()->json([
            'status' => true,
            "message" => 'تأكد من البيانات المدخلة',
            'data' => ""
        ], 401);
    }

    public function resetPassword(Request $request)
    {
        // Validate the incoming request data
        $request->validate([
            'phone' => 'required|string|max:15',
        ]);

        $user = User::firstWhere('phone',$request->phone);
        if (!$user) {
            return response()->json([
                'status' => false,
                "message" => 'لم يتم العثور على هذا الرقم',
                'data' => ""
            ], 404);
        }
        $new_password = rand(100000,999999);
        $user->update([
            'password' => bcrypt($new_password)
        ]);

        return response()->json([
            'status' => true,
            "message" => 'تم ارسال الرقم السري الجديد في رسالة نصية',
            'data' => ['new_password' => $new_password]
        ], 200);

    }

    public function logout()
    {
        auth()->user()->tokens()->delete();
        return response()->json([
            'status' => true,
            "message" => 'تم تسجيل الخروج بنجاح',
            'data' => ""
        ], 200);
    }
}

app/Http/Controllers/Api/User/OrderController.php
<?php

namespace App\Http\Controllers\Api\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\OrderRequest;
use App\Http\Resources\User\OrderResource;
use App\Models\Order;
use App\Models\Package;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    public function index(Request $request)
    {
        $orders = Order::when($request->status, function ($q) use ($request) {
            return $q->where('status', $request->status);
        })->get();

        return response()->json([
            'status' => true,
            "message" => '',
            'data' => OrderResource::collection($orders)
        ], 200);
    }

    public function store(OrderRequest $request)
    {
        // Start the database transaction
        \DB::beginTransaction();

        try {
            // Validate the request data
            $data = $request->validated();
            $package_data = $request->only(['title', 'weight', 'car', 'phone', 'date', 'note']);
            $order_data = $request->except('title', 'weight', 'car', 'phone', 'date', 'note');
            // store package data
            $package = Package::create($package_data + ['user_id' => auth()->id()]);

            // store order data
            $order = Order::create($order_data + [
                    'package_id' => $package->id,
                    'user_id' => auth()->id(),
                    'status' => 'pending',
                ]);
            // store order data
            // Commit the database transaction
            \DB::commit();
            return response()->json([
                'status' => true,
                "message" => 'تم ارسال الطلب بنجاح',
                'data' => OrderResource::make($order)
            ], 200);
        } catch (\Exception $e) {
            // An error occurred, rollback the database transaction
            \DB::rollBack();
            // Optionally log the error or handle it in another way
            return response()->json([
                'status' => true,
                "message" => 'حدث خطأ ما',
                'data' => ''
            ], 422);
        }
    }

    public function show($id)
    {
        $order = Order::findOrFail($id);
        return response()->json([
            'status' => true,
            "message" => '',
            'data' => OrderResource::make($order)
        ], 200);
    }


    public function delete($id)
    {
        $order = Order::findOrFail($id);
        if ($order->status != 'pending') {
            return response()->json([
                'status' => false,
                "message" => 'لا يمكن حذف طلب الان',
                'data' => ''
            ], 200);
        }

        $order->delete();

        return response()->json([
            'status' => true,
            "message" => 'تم حذف الطلب بنجاح',
            'data' => ""
        ], 200);
    }


    public function cancel($id)
    {
        $order = Order::findOrFail($id);
        if ($order->status != 'pending') {
            return response()->json([
                'status' => false,
                "message" => 'لا يمكن الغاء طلب الان',
                'data' => ''
            ], 200);
        }

        $order->update(['status' => 'canceled']);

        return response()->json([
            'status' => true,
            "message" => 'تم الغاء الطلب بنجاح',
            'data' => ""
        ], 200);
    }
}

app/Http/Controllers/Api/User/ProfileController.php
<?php

namespace App\Http\Controllers\Api\User;

use App\Http\Controllers\Controller;
use App\Http\Resources\User\UserResource;
use Illuminate\Http\Request;

class ProfileController extends Controller
{
    public function show()
    {
        return response()->json([
            'status' => true,
            "message" => '',
            'data' => UserResource::make(auth()->user())
        ], 200);
    }

    public function update(Request $request)
    {
        auth()->user()->update($request->all());
        return response()->json([
            'status' => true,
            "message" => 'تم التحديث بنجاح',
            'data' => UserResource::make(auth()->user())
        ], 200);
    }

    public function updatePicture(Request $request)
    {
        // Validate the incoming request (e.g., check for file type, size, etc.)
        $request->validate([
            'image' => 'required|image|mimes:jpeg,png,jpg,gif|max:2048',
        ]);

        // Handle file upload
        $profilePicture = $request->file('image');
        $fileName = time() . '_' . \Str::random(15) . '.' . $profilePicture->getClientOriginalExtension();
        $profilePicture->move(public_path('images'), $fileName);

        // Update user's profile picture field in the database
        auth()->user()->update(['image' => $fileName]);

        return response()->json([
            'status' => true,
            "message" => 'تم التحديث بنجاح',
            'data' => UserResource::make(auth()->user())
        ], 200);
    }

    public function changePassword(Request $request)
    {
        $user = auth()->user();

        // Validate the incoming request
        $request->validate([
            'old_password' => 'required|string',
            'new_password' => 'required|string|min:8',
            'confirm_password' => 'required|string|same:new_password',
        ]);

        // Check if the provided old password matches the current password
        if (!\Hash::check($request->old_password, $user->password)) {
            return response()->json([
                'status' => true,
                "message" => 'كلمة المرور الحالية غير صحيحة',
                'data' => ""
            ], 401);
        }

        // Update user's password in the database
        $user->update([
            'password' => \Hash::make($request->new_password),
        ]);

        return response()->json([
            'status' => true,
            "message" => 'تم التحديث بنجاح',
            'data' => UserResource::make(auth()->user())
        ], 200);
    }

    public function deleteAccount()
    {
        auth()->user()->delete();
        return response()->json([
            'status' => true,
            "message" => 'تم حذف الحساب بنجاح',
            'data' => ""
        ], 200);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    // Display a listing of the users
    public function showLoginForm()
    {
        return view('login');
    }

    // Login function
    public function login(Request $request)
    {
        // Validate the request data
        $request->validate([
            'phone' => ['required', 'string', 'max:255'],
            'password' => 'required',
        ]);
        // Attempt to log in the user
        $credentials = $request->only('phone', 'password');
        if (Auth::attempt($credentials)) {
            // Authentication passed
            return redirect()->intended('/admin/dashboard');
        }
        // Authentication failed
        return back()->withErrors(['email' => 'Invalid credentials'])->withInput($request->only('email'));
    }

    // Log the user out
    public function logout()
    {
        Auth::logout();
        return redirect('/login');
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.app')
@section('content')
    <!-- /.card-header -->

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">الرئيسية - اضافة العملاء</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/dashboard">الرئيسية</a></li>
                        <li class="breadcrumb-item active"> اضافة العملاء</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <!-- form start -->
                <form role="form" method='post' action="{{ route('users.store') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="card-body">
                        @if($errors->any())
                            <div class="alert alert-danger text-center">
                                <ul>
                                    @foreach($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <!-- Name -->
                        <div class="form-group">
                            <label for="name">الاسم</label>
                            <input type="text" required name="name" value="{{ old('name') }}" class="form-control"/>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputFile">الصورة </label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="exampleInputFile" name="image">
                                    <label class="custom-file-label" for="exampleInputFile"></label>
                                </div>
                                <div class="input-group-append">
                                    <br><br>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="phone">رقم الهاتف</label>
                            <input type="text" required name="phone" value="{{ old('phone') }}"
                                   class="form-control"/>
                        </div>

                        <div class="form-group">
                            <label for="password">كلمة المرور</label>
                            <input type="password" required name="password" class="form-control"/>
                        </div>
                        <!-- Phone Number -->

                        <input type="hidden" name="user_type" value="user">
                        <div>
                            <button type="submit" class="btn btn-primary">تأكيد</button>
                        </div>
                    </div>

                    <!-- /.card-body -->
                </form>
            </div>
        </div>
    </section>
    <!-- /.card -->
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">الرئيسية - تعديل بيانات العميل</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/dashboard">الرئيسية</a></li>
                        <li class="breadcrumb-item active">تعديل بيانات العميل</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <form action="{{ route('users.update', $patient->id) }}" method="post"
                          enctype="multipart/form-data" class="mx-auto">
                        @csrf
                        @method('PUT')
                        <div class="card-body">
                            <!-- Name -->
                            <div class="form-group">
                                <label for="exampleInputText1">الاسم</label>
                                <input type="text" class="form-control" name="name" id="exampleInputText1"
                                       placeholder="ادخل الاسم" value="{{ $patient->user->name }}">
                            </div>

                            <!-- Age -->
                            <div class="form-group">
                                <label for="exampleInputText1">العمر</label>
                                <input type="number" class="form-control" name="age" id="exampleInputText1"
                                       placeholder="ادخل العمر" value="{{ $patient->age }}">
                            </div>

                            <!-- Email -->
                            <div class="form-group">
                                <label for="exampleInputEmail1">البريد الإلكتروني</label>
                                <input type="email" class="form-control" name="email" id="exampleInputEmail1"
                                       placeholder="ادخل البريد الإلكتروني" value="{{ $patient->user->email }}">
                            </div>

                            <!-- Password -->
                            <div class="form-group">
                                <label for="exampleInputPassword1">كلمة المرور</label>
                                <input type="password" class="form-control" name="password" id="exampleInputPassword1"
                                       placeholder="ادخل كلمة المرور">
                            </div>

                            <!-- Phone Number -->
                            <div class="form-group">
                                <label for="exampleInputEmail1">رقم الهاتف</label>
                                <input type="text" class="form-control" name="phone" id="exampleInputText1"
                                       placeholder="ادخل رقم الهاتف" value="{{ $patient->user->phone }}">
                            </div>

                            <div class="form-group">
                                <label for="exampleInputFile">الصوره</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="exampleInputFile" name="image">
                                        <label class="custom-file-label" for="exampleInputFile"></label>
                                    </div>
                                    <div class="input-group-append">
                                        <br><br>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <button type="submit" class="btn btn-primary">تعديل</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark"> الرئيسية - قائمة العملاء</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/dashboard">الرئيسية</a></li>
                        <li class="breadcrumb-item active">قائمة العملاء</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- /.content-header -->
    @include('admin.layouts.message')
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title" style="float: right">قائمة العملاء</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>الاسم</th>
                                <th>الصورة</th>
                                <th>الموبايل</th>
                                <th>الاجراء المتخذ</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($users as $user)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>
                                        @if($user->image)
                                            <img src="{{ asset('uploads/' . $user->image) }}" alt="{{ $user->name }}" class="img-thumbnail" style="max-width: 50px; max-height: 50px;">
                                        @else
                                            No Image
                                        @endif
                                    </td>
                                    <td>{{ $user->phone }}</td>
                                    <td>
                                        <a href="{{ route('users.edit', $user->id) }}" class="btn btn-warning btn-sm">تعديل</a>
                                        <form action="{{ route('users.destroy', $user->id) }}" method="post" style="display: inline-block;">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('هل أنت متأكد؟')">حذف</button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="5" class="text-center">لا يوجد بيانات</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/users/show.blade.php
@extends('admin.layouts.app')


@section('content')
    <div class="content">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark"> الرئيسية - تفاصيل العملاء</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/dashboard">الرئيسية</a></li>
                            <li class="breadcrumb-item active">تفاصيل العملاء</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <section class="content">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="card">
                        <img src="{{ $user->image ? asset('uploads/' . $user->image) : asset('images/no-image.png') }}" class="card-img-top img-fluid mx-auto d-block w-25" alt="{{ $user->name }}">
                        <div class="card-body text-center">
                            <h2 class="text-center">{{ $user->name }}</h2>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <strong>رقم الهاتف</strong><br>
                                {{ $user->user->phone }}
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection