routes/web.php
<?php

use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\DriverController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Authenticated routes
Route::middleware('web')->group(function () {


    // تسجيل الدخول لمسءول النظام
    Route::get('/', [UserController::class, 'showLoginForm'])->name('showLoginForm');
    Route::get('admin/login', [UserController::class, 'showLoginForm'])->name('showLoginForm');
    Route::post('admin/login', [UserController::class, 'login'])->name('doLogin');
    //    تسجيل الخروج لمسءول النظام
    Route::get('/logout', [UserController::class, 'logout'])->name('logout');

    // Dashboard route (protected by auth middleware)
    Route::middleware(['auth'])->group(function () {
        // لوحة التحكم
        Route::prefix('admin')->group(function () {
            Route::get('/dashboard', [HomeController::class, 'home'])->name('homeDashboard');
            Route::resource('users', ClientController::class);
            Route::resource('drivers', DriverController::class);
            Route::resource('orders', OrderController::class);
        });
    });

});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{

    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo(User::class,'user_id');
    }
    public function driver()
    {
        return $this->belongsTo(User::class,'driver_id');
    }

    public function package()
    {
        return $this->belongsTo(Package::class);
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\User;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    public function index()
    {
        $orders = Order::all();
        $active = 'orders';
        return view('admin.orders.index', compact('orders','active'));
    }

    public function create()
    {
       //
    }

    public function store(Request $request)
    {
        //
    }


    public function show($id)
    {
        $order = Order::findOrFail($id);
        $active = 'orders';
        return view('admin.orders.show', compact('order','active'));
    }

    public function edit($id)
    {
        $order = Order::findOrFail($id);
        $drivers = User::where('user_type','driver')->latest()->get();
        $active = 'orders';
        return view('admin.orders.edit', compact('order','drivers','active'));
    }

    public function update(Request $request, $id)
    {
        // Find the doctor by ID
        $order = Order::findOrFail($id);
        $order->update($request->all());
        // Redirect to the index route
        return redirect()->route('orders.index')->with('success', 'تم تعديل الطلب بنجاح');
    }


    public function destroy($id)
    {
        $order = Order::findOrFail($id);

        $order->delete();

        return redirect()->route('orders.index')->with('success', 'تم مسح الطلب بنجاح.');
    }
}

app/Http/Controllers/Api/User/OrderController.php
<?php

namespace App\Http\Controllers\Api\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\OrderRequest;
use App\Http\Resources\User\OrderResource;
use App\Models\Order;
use App\Models\Package;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    public function index(Request $request)
    {
        $orders = Order::when($request->status, function ($q) use ($request) {
            return $q->where('status', $request->status);
        })->get();

        return response()->json([
            'status' => true,
            "message" => '',
            'data' => OrderResource::collection($orders)
        ], 200);
    }

    public function store(OrderRequest $request)
    {
        // Start the database transaction
        \DB::beginTransaction();

        try {
            // Validate the request data
            $data = $request->validated();
            $package_data = $request->only(['title', 'weight', 'car', 'phone', 'date', 'note']);
            $order_data = $request->except('title', 'weight', 'car', 'phone', 'date', 'note');
            // store package data
            $package = Package::create($package_data + ['user_id' => auth()->id()]);

            // store order data
            $order = Order::create($order_data + [
                    'package_id' => $package->id,
                    'user_id' => auth()->id(),
                    'status' => 'pending',
                ]);
            // store order data
            // Commit the database transaction
            \DB::commit();
            return response()->json([
                'status' => true,
                "message" => 'تم ارسال الطلب بنجاح',
                'data' => OrderResource::make($order)
            ], 200);
        } catch (\Exception $e) {
            // An error occurred, rollback the database transaction
            \DB::rollBack();
            // Optionally log the error or handle it in another way
            return response()->json([
                'status' => true,
                "message" => 'حدث خطأ ما',
                'data' => ''
            ], 422);
        }
    }

    public function show($id)
    {
        $order = Order::findOrFail($id);
        return response()->json([
            'status' => true,
            "message" => '',
            'data' => OrderResource::make($order)
        ], 200);
    }


    public function delete($id)
    {
        $order = Order::findOrFail($id);
        if ($order->status != 'pending') {
            return response()->json([
                'status' => false,
                "message" => 'لا يمكن حذف طلب الان',
                'data' => ''
            ], 200);
        }

        $order->delete();

        return response()->json([
            'status' => true,
            "message" => 'تم حذف الطلب بنجاح',
            'data' => ""
        ], 200);
    }


    public function cancel($id)
    {
        $order = Order::findOrFail($id);
        if ($order->status != 'pending') {
            return response()->json([
                'status' => false,
                "message" => 'لا يمكن الغاء طلب الان',
                'data' => ''
            ], 200);
        }

        $order->update(['status' => 'canceled']);

        return response()->json([
            'status' => true,
            "message" => 'تم الغاء الطلب بنجاح',
            'data' => ""
        ], 200);
    }
}

resources/views/admin/orders/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">الرئيسية - تعديل بيانات الطلب</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/dashboard">الرئيسية</a></li>
                        <li class="breadcrumb-item active">تعديل بيانات الطلب</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <form action="{{ route('orders.update', $order->id) }}" method="post"
                          enctype="multipart/form-data" class="mx-auto">
                        @csrf
                        @method('PUT')
                        <div class="card-body">
                            <div class="form-group">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>بيانات الطلب</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    <tr>
                                        <td>صاحب الطلب</td>
                                        <td>{{ $order->user->name }}</td>
                                    </tr>
                                    <tr>
                                        <td>اسم الشحنة</td>
                                        <td>{{ $order->package->title }}</td>
                                    </tr>
                                    <tr>
                                        <td>الوزن</td>
                                        <td>{{ $order->package->weight }}</td>
                                    </tr>

                                    <tr>
                                        <td>الموبايل</td>
                                        <td>{{ $order->package->phone }}</td>
                                    </tr>

                                    <tr>
                                        <td>تاريخ الطلب</td>
                                        <td>{{ $order->package->date }}</td>
                                    </tr>

                                    <tr>
                                        <td>حالة الطلب</td>
                                        <td>{{  $order->status=='completed'?'مكتملة'
                                            : ($order->status=='pending'?'قيد الانتظار'
                                            :($order->status=='in_progress'?'جاري التنفيذ':'ملغية')) }}</td>
                                    </tr>

                                    <tr>
                                        <td>السائق</td>
                                        <td>{{ $order->driver->name??'لا يوجد' }}</td>
                                    </tr>
                                    <!-- Add more rows as needed -->
                                    </tbody>
                                    </table>

                                <div class="form-group">
                                    <label for="status">تغيير حالة الطلب</label>
                                    <select name="status" id="" class="form-control">
                                        <option value="pending" @if($order->status=='pending') selected @endif>قيد الانتظار</option>
                                        <option value="in_progress" @if($order->status=='in_progress') selected @endif>جاري التنفيذ</option>
                                        <option value="completed" @if($order->status=='completed') selected @endif>مكتملة</option>
                                        <option value="canceled" @if($order->status=='canceled') selected @endif>ملغية</option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="status">تغيير السائق</label>
                                    <select name="driver_id" id="" class="form-control">
                                        @foreach($drivers as $driver)
                                            <option value="{{ $driver->id }}" @if($order->driver_id==$driver->id) selected @endif>
                                                {{ $driver->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>

                                <button type="submit" class="btn btn-primary">تعديل</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/orders/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark"> الرئيسية - قائمة الطلبات</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/dashboard">الرئيسية</a></li>
                        <li class="breadcrumb-item active">قائمة الطلبات</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- /.content-header -->
    @include('admin.layouts.message')
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title" style="float: right">قائمة الطلبات</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>الاسم</th>
                                <th>الموبايل</th>
                                <th>الحالة</th>
                                <th>السائق</th>
                                <th>الاجراء المتخذ</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($orders as $order)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $order->user->name }}</td>
                                    <td>{{ $order->user->phone }}</td>
                                    <td>{{  $order->status=='completed'?'مكتملة'
                                            : ($order->status=='pending'?'قيد الانتظار'
                                            :($order->status=='in_progress'?'جاري التنفيذ':'ملغية')) }}</td>
                                    <td>{{ $order->driver->name??'لا يوجد' }}</td>
                                    <td>
                                        <a href="{{ route('orders.edit', $order->id) }}" class="btn btn-warning btn-sm">تعديل</a>
                                        <form action="{{ route('orders.destroy', $order->id) }}" method="post"
                                              style="display: inline-block;">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm"
                                                    onclick="return confirm('هل أنت متأكد؟')">حذف
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="6" class="text-center">لا يوجد بيانات</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/orders/show.blade.php
@extends('admin.layouts.app')


@section('content')
    <div class="content">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark"> الرئيسية - تفاصيل العملاء</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/dashboard">الرئيسية</a></li>
                            <li class="breadcrumb-item active">تفاصيل العملاء</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <section class="content">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="card">
                        <img src="{{ $user->image ? asset('uploads/' . $user->image) : asset('images/no-image.png') }}" class="card-img-top img-fluid mx-auto d-block w-25" alt="{{ $user->name }}">
                        <div class="card-body text-center">
                            <h2 class="text-center">{{ $user->name }}</h2>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <strong>رقم الهاتف</strong><br>
                                {{ $user->user->phone }}
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection